### ISSUE TITLE
Please add explicit license note.

### ISSUE THREAD

**Issue by Maniues** [FDOS/sys#1]

**Comment by PerditionC** [comment]
license is GPL v2, as this was originally part of the kernel; to be updated to reflect license

**Comment by PerditionC** [comment]
done, see commit 120b31d159496e23a0cf8ea20cc059db7f82859a

**Comment by ecm-pushbx** [comment]
Technically, the license is GPL v2-or-later. This depends on the exact wording in the source files' headers.
