### ISSUE TITLE
-

### ISSUE THREAD

**Issue by cuj** [FDOS/sys#2]
>

**Comment by PerditionC** [comment]
sys does not work for ISO images - you can either create a floppy/hard drive image using sys and when creating the ISO image tell the tool you are using to create a bootable image using the floppy/hard drive image or use a boot loader that works for cd roms and can directly load the kernel.  The simplest case is to run sys on a virtual floppy and use that image or use a real floppy and use a tool such as rawread to get the image file.   Depending on what operating system you are using, you will want to look into a program such as mkisofs/cdrtools and grub/syslinux.

**Comment by cuj** [comment]
Hi, I am the author of this issue, so I should be able to delete this issue, but for some reason GitHub does not allow the author of an issue to delete his own issue, so all I can do is request you, @PerditionC, to delete my issue. So Can you please delete my issue? thanks.
